package ohos_app_cangjie_entry.ui.theme

public let GrayBackground: Int64 = 0xFFF2F3F2
public let GrayBackgroundSecond: Int64 = 0xFFEBEBEB
public let Black: Int64 = 0xFF181725
public let Green: Int64 = 0xFF53B175
public let GrayTextColor: Int64 = 0xFFFCFCFC
public let GraySecondTextColor: Int64 = 0xFF7C7C7C
public let GrayThirdTextColor: Int64 = 0xFF4C4F4D
public let GrayBorderStroke: Int64 = 0xFFE2E2E2
public let BackgroundCategory1: Int64 = 0xFFEEF8F2
public let BackgroundCategory2: Int64 = 0xFFFFF6EE
public let BackgroundCategory3: Int64 = 0xFFFDE8E4
public let BackgroundCategory4: Int64 = 0xFFF4EBF7
public let BackgroundCategory5: Int64 = 0xFFFEF8E5
public let BackgroundCategory6: Int64 = 0xFFEDF7FC