package ohos_app_cangjie_entry.ui.theme

public let DIMENS_4vp: Int64 = 4
public let DIMENS_8vp: Int64 = 8
public let DIMENS_12vp: Int64 = 12
public let DIMENS_16vp: Int64 = 16
public let DIMENS_20vp: Int64 = 20
public let DIMENS_24vp: Int64 = 24
public let DIMENS_32vp: Int64 = 32
public let TEXT_SIZE_12fp: Int64 = 12
public let TEXT_SIZE_16fp: Int64 = 16
public let TEXT_SIZE_18fp: Int64 = 18
public let TEXT_SIZE_24fp: Int64 = 24
public let TEXT_SIZE_49fp: Int64 = 49