package ohos_app_cangjie_entry.navigation

public let NAV_HOME_ROUTE: String = "home_screen"
public let NAV_HOME_TITLE: String = "Shop"
public let NAV_EXPLORE_ROUTE: String = "explore_screen"
public let NAV_EXPLORE_TITLE: String = "Explore"
public let NAV_CART_ROUTE: String = "cart_screen"
public let NAV_CART_TITLE: String = "Cart"
public let NAV_ABOUT_ROUTE: String = "about_screen"
public let NAV_ABOUT_TITLE: String = "About"